@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(order_orchestrator, "Order Orchestrator", "Camunda")
Container(payment_service, "Payment Service", "Kotlin/Spring Boot")
Container(fraud_check_service, "Fraud Check Service", "Kotlin/Spring Boot")
Container(notification_service, "Notification Service", "Kotlin/Spring Boot")

Rel(order_orchestrator, payment_service, "Начинает транзакцию оплаты")
Rel(order_orchestrator, fraud_check_service, "Требует начать проверку на фрод")
Rel(fraud_check_service, notification_service, "Уведомление о статусе проверки на фрод")
Rel(order_orchestrator, payment_service, "Начинает транзакцию 'Перевод денег контрагенту'")


@enduml
