@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(payment_service, "Payment Service") {
  Component(marketplace_order_orchestrator, "Marketplace order orchestrator", "Camunda")
  Component(payment_service_functionality, "Payment Service Functionality", "Функциональность обработки платежей и проч.")
}

Container(fraud_check_service, "Fraud Check Service", "Kotlin/Spring Boot")
Container(notification_service, "Notification Service", "Kotlin/Spring Boot")

Rel(marketplace_order_orchestrator, payment_service_functionality, "Начинает транзакцию оплаты")
Rel(marketplace_order_orchestrator, fraud_check_service, "Требует начать проверку на фрод")
Rel(fraud_check_service, notification_service, "Уведомление о статусе проверки на фрод")
Rel(marketplace_order_orchestrator, payment_service_functionality, "Начинает транзакцию 'Перевод денег контрагенту'")

@enduml
